### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by floriandierickx** [tobyqin/Typora-Portable#2]
hey @tobyqin , a big thank you for having provided a portable version, it saved my day (and coming months! :) ). Out of curiosity: do you plan to provide an updated version of the latest beta? Don't have any idea how much time it takes to do so, so it's just a curiosity-question...

**Comment by tobyqin** [comment]
You are welcome @floriandierickx, it does not take me too much time to prepare a new version, just depends on my time and ... if it is a breaking change version.

Anyway, I just published the latest version just now.

 - https://github.com/tobyqin/Typora-Portable/releases/tag/0.9.83
