### ISSUE TITLE
Alt method

### ISSUE THREAD

**Issue by locobastos** [tobyqin/Typora-Portable#3]
Hello !

You can also use Universal Extractor to extract the InnoSetup file.
Worked using Universal Extractor 1.6.1 and Typora 0.9.98.

Best Regards.

**Comment by tobyqin** [comment]
Sounds great, let me give it a try!

**Comment by xuanyuanaosheng** [comment]
@tobyqin  还更新么？

**Comment by tobyqin** [comment]
@xuanyuanaosheng any good features in latest version?

**Comment by tobyqin** [comment]
@xuanyuanaosheng  0.9.98 published
https://github.com/tobyqin/Typora-Portable/releases/tag/0.9.98
