### ISSUE TITLE
Any plan to support the new version of typora

### ISSUE THREAD

**Issue by lingliugithub** [tobyqin/Typora-Portable#5]
I see the latest avaialble varion of Typora is not converted to portable version...
Any plan to do the portable coversion for more recent Typora?

**Comment by tobyqin** [comment]
we can do it, let me check the new features

**Comment by 02015678** [comment]
Look forward to see Portable version 0.11.18, since Typora is no longer free starting from 1.0

**Comment by tobyqin** [comment]
done.
